blank_issues_enabled: false
contact_links:
  - name: Questions / Discussion
    url: https://github.com/printemps-tokyo/ytsum/discussions
    about: For questions that are not bug reports or feature requests
